/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInput: typeof import('./src/components/page_compoents/UserInput.vue')['default']
    UserStatusCard: typeof import('./src/components/page_compoents/UserStatusCard.vue')['default']
    UserToggleButton: typeof import('./src/components/page_compoents/UserToggleButton.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
    YButton: typeof import('./src/components/y_compoents/YButton.vue')['default']
    YButtonCard: typeof import('./src/components/y_compoents/YButtonCard.vue')['default']
    YCard: typeof import('./src/components/y_compoents/YCard.vue')['default']
    YchoiceCard: typeof import('./src/components/y_compoents/YchoiceCard.vue')['default']
    YInput: typeof import('./src/components/y_compoents/YInput.vue')['default']
    YLoading: typeof import('./src/components/y_compoents/YLoading.vue')['default']
    YNavBar: typeof import('./src/components/y_compoents/YNavBar.vue')['default']
  }
}
